name: Build and test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-file: "go.mod"

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - ubuntu
          - macos
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: arduino/setup-task@v2
      - name: Setup dependencies
        run: task setup
      - name: Build
        run: task build
      - name: Run tests
        run: task test
