name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Write in private key
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > ${{ github.workspace }}/cosign.key
      - name: release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PWD }}
